version: 2
updates:
  # npm in root workspace (tools, hooks)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # npm in app package
  - package-ecosystem: "npm"
    directory: "/linux-ai-assistant"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # cargo for top-level Tauri crate
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # cargo for app Tauri crate
  - package-ecosystem: "cargo"
    directory: "/linux-ai-assistant/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
