version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/linux-ai-assistant"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "/linux-ai-assistant"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
