name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev pkg-config build-essential

      - name: Install npm dependencies
        run: |
          cd linux-ai-assistant
          npm ci

      - name: Build frontend
        run: |
          cd linux-ai-assistant
          npm run build

      - name: Build Tauri backend
        run: |
          cd linux-ai-assistant/src-tauri
          cargo build --release

      - name: Upload Tauri binary
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app
          path: linux-ai-assistant/src-tauri/target/release/
