#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint-staged on staged files. Requires project devDeps: husky + lint-staged + prettier
npx --no-install lint-staged
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint-staged on staged files
npx --no -- lint-staged
